# Source: opentelemetry-demo/templates/component.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels:
    
    opentelemetry.io/name: postgresql
    
    app.kubernetes.io/component: postgresql
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: "2.1.3"
    app.kubernetes.io/part-of: opentelemetry-demo
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      
      opentelemetry.io/name: postgresql
  template:
    metadata:
      labels:
        
        opentelemetry.io/name: postgresql
        
        app.kubernetes.io/component: postgresql
        app.kubernetes.io/name: postgresql
    spec:
      serviceAccountName: opentelemetry-demo
      containers:
        - name: postgresql
          image: 'ghcr.io/open-telemetry/demo:2.1.3-postgresql'
          imagePullPolicy: IfNotPresent
          ports:
            
            - containerPort: 5432
              name: service
          env:
            - name: OTEL_SERVICE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels['app.kubernetes.io/component']
            - name: OTEL_COLLECTOR_NAME
              value: otel-collector
            - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
              value: cumulative
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PASSWORD
              value: otel
            - name: POSTGRES_DB
              value: otel
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.name=$(OTEL_SERVICE_NAME),service.namespace=opentelemetry-demo,service.version=2.1.3
          resources:
            limits:
              memory: 100Mi
          volumeMounts:
      volumes:
---